# Generated by mxlweb-core KineticModelBuilder.buildMxlpy() — see test_units.py.
import math

import numpy as np
import sympy.physics.units as su
from sympy.physics.units.quantities import Quantity

from mxlpy import Model

def _rate_v1(S, vmax, km):
    return (vmax * S) / (km + S)

def _rate_v2(P, k_out):
    return k_out * P

def get_model() -> Model:
    m = Model()
    m.add_parameter("vmax", 1, unit=su.mol*su.milli/su.second)
    m.add_parameter("km", 0.5, unit=su.mol*su.milli)
    m.add_parameter("k_out", 0.1, unit=1/su.second)
    m.add_parameter("light", 100, unit=su.mol*su.micro/(su.meter**2*su.second))
    m.add_parameter("od", 0.4, unit=Quantity("OD600", abbrev="OD600"))
    m.add_variable("S", 1, unit=su.mol*su.milli)
    m.add_variable("P", 0, unit=su.mol*su.milli)
    m.add_reaction(
        "v1",
        _rate_v1,
        args=["S", "vmax", "km"],
        stoichiometry={"S": -1, "P": 1},
        unit=su.mol*su.milli/su.second,
    )
    m.add_reaction(
        "v2",
        _rate_v2,
        args=["P", "k_out"],
        stoichiometry={"P": -1},
    )
    return m
