repos:
  - repo: https://github.com/hakancelikdev/unexport
    rev: 0.4.0
    hooks:
      - id: unexport
        args: [--refactor, --exclude tests]

  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

  - repo: https://github.com/aio-libs/sort-all
    rev: v1.3.0
    hooks:
      - id: sort-all
