site_name: modelbase docs
site_url: https://qtb-hhu.gitlab.io/modelbase-software/
site_dir: public

nav:
  - Overview: index.md
  - Basics: basics.ipynb
  - Scans: scans.ipynb
  - MCA: mca.ipynb
  - Fitting: fitting.ipynb
  - Monte-Carlo: monte-carlo.ipynb
  - Mechanistic-Learning: mxl.ipynb
  - Label-Models: label-models.ipynb

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
      execute: false
      ignore: ["assets/*.ipynb"]

markdown_extensions:
  - attr_list
