from __future__ import annotations

from mxlpy.meta import generate_mxlpy_code_raw
from tests import models


def test_generate_model_code_py_m_1v_0p_0d_0r() -> None:
    assert generate_mxlpy_code_raw(models.m_1v_0p_0d_0r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "    )",
    ]


def test_generate_model_code_py_m_2v_0p_0d_0r() -> None:
    assert generate_mxlpy_code_raw(models.m_2v_0p_0d_0r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_variable('v2', initial_value=2.0)",
        "    )",
    ]


def test_generate_model_code_py_m_0v_1p_0d_0r() -> None:
    assert generate_mxlpy_code_raw(models.m_0v_1p_0d_0r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_parameter('p1', value=1.0)",
        "    )",
    ]


def test_generate_model_code_py_m_0v_2p_0d_0r() -> None:
    assert generate_mxlpy_code_raw(models.m_0v_2p_0d_0r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_parameter('p1', value=1.0)",
        "        .add_parameter('p2', value=2.0)",
        "    )",
    ]


def test_generate_model_code_py_m_1v_1p_1d_0r() -> None:
    assert generate_mxlpy_code_raw(models.m_1v_1p_1d_0r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_ADD_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_parameter('p1', value=1.0)",
        "        .add_derived(",
        "                'd1',",
        "                fn=add,",
        "                args=['v1', 'p1'],",
        "            )",
        "    )",
    ]


_ADD_LINES = [
    "def add(x: float, y: float) -> float:",
    '    """Calculate the sum of two values.',
    "",
    "    Parameters",
    "    ----------",
    "    x",
    "        First addend",
    "    y",
    "        Second addend",
    "",
    "    Returns",
    "    -------",
    "    Float",
    "        Sum of x and y (x + y)",
    "",
    "    Examples",
    "    --------",
    "    >>> add(2.0, 3.0)",
    "    5.0",
    "    >>> add(-1.5, 3.5)",
    "    2.0",
    "",
    '    """',
    "    return x + y",
]

_MUL_LINES = [
    "def mul(x: float, y: float) -> float:",
    '    """Calculate the product of two values.',
    "",
    "    Parameters",
    "    ----------",
    "    x",
    "        First factor",
    "    y",
    "        Second factor",
    "",
    "    Returns",
    "    -------",
    "    Float",
    "        Product of x and y (x * y)",
    "",
    "    Examples",
    "    --------",
    "    >>> mul(2.0, 3.0)",
    "    6.0",
    "    >>> mul(0.5, 4.0)",
    "    2.0",
    "",
    '    """',
    "    return x * y",
]

_MASS_ACTION_1S_LINES = [
    "def mass_action_1s(s1: float, k: float) -> float:",
    '    """Calculate irreversible mass action reaction rate with one substrate.',
    "",
    "    Rate = k * [S]",
    "",
    "    Parameters",
    "    ----------",
    "    s1",
    "        Substrate concentration",
    "    k",
    "        Rate constant",
    "",
    "    Returns",
    "    -------",
    "    Float",
    "        Reaction rate",
    "",
    "    Examples",
    "    --------",
    "    >>> mass_action_1s(2.0, 0.5)  # Rate = 0.5 * [S]",
    "    1.0",
    "    >>> # Example: Simple degradation reaction S -> \u2205",
    "    >>> mass_action_1s(5.0, 0.2)  # Rate = 0.2 * [S]",
    "    1.0",
    "",
    '    """',
    "    return k * s1",
]

_CONSTANT_LINES = [
    "def constant(x: float) -> float:",
    '    """Return a constant value regardless of other model components.',
    "",
    "    Parameters",
    "    ----------",
    "    x",
    "        Value to return",
    "",
    "    Returns",
    "    -------",
    "    Float",
    "        The input value unchanged",
    "",
    "    Examples",
    "    --------",
    "    >>> constant(5.0)",
    "    5.0",
    "",
    '    """',
    "    return x",
]

_ONE_DIV_LINES = [
    "def one_div(x: float) -> float:",
    '    """Calculate the reciprocal of a value.',
    "",
    "    Parameters",
    "    ----------",
    "    x",
    "        Value to find reciprocal of",
    "",
    "    Returns",
    "    -------",
    "    Float",
    "        Reciprocal of x (1 / x)",
    "",
    "    Examples",
    "    --------",
    "    >>> one_div(2.0)",
    "    0.5",
    "    >>> one_div(4.0)",
    "    0.25",
    "",
    '    """',
    "    return 1.0 / x",
]


def test_generate_model_code_py_m_1v_1p_1d_1r() -> None:
    assert generate_mxlpy_code_raw(models.m_1v_1p_1d_1r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_ADD_LINES,
        "",
        "",
        *_MASS_ACTION_1S_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_parameter('p1', value=1.0)",
        "        .add_derived(",
        "                'd1',",
        "                fn=add,",
        "                args=['v1', 'p1'],",
        "            )",
        "        .add_reaction(",
        '                "r1",',
        "                fn=mass_action_1s,",
        "                args=['v1', 'd1'],",
        '                stoichiometry={"v1": -1.0},',
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_2v_1p_1d_1r() -> None:
    assert generate_mxlpy_code_raw(models.m_2v_1p_1d_1r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_ADD_LINES,
        "",
        "",
        *_MASS_ACTION_1S_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_variable('v2', initial_value=2.0)",
        "        .add_parameter('p1', value=1.0)",
        "        .add_derived(",
        "                'd1',",
        "                fn=add,",
        "                args=['v1', 'v2'],",
        "            )",
        "        .add_reaction(",
        '                "r1",',
        "                fn=mass_action_1s,",
        "                args=['v1', 'p1'],",
        '                stoichiometry={"v1": -1.0,"v2": 1.0},',
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_2v_2p_1d_1r() -> None:
    assert generate_mxlpy_code_raw(models.m_2v_2p_1d_1r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_ADD_LINES,
        "",
        "",
        *_MASS_ACTION_1S_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_variable('v2', initial_value=2.0)",
        "        .add_parameter('p1', value=1.0)",
        "        .add_parameter('p2', value=2.0)",
        "        .add_derived(",
        "                'd1',",
        "                fn=add,",
        "                args=['v1', 'v2'],",
        "            )",
        "        .add_reaction(",
        '                "r1",',
        "                fn=mass_action_1s,",
        "                args=['v1', 'p1'],",
        '                stoichiometry={"v1": -1.0,"v2": 1.0},',
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_2v_2p_2d_1r() -> None:
    assert generate_mxlpy_code_raw(models.m_2v_2p_2d_1r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_ADD_LINES,
        "",
        "",
        *_MUL_LINES,
        "",
        "",
        *_MASS_ACTION_1S_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_variable('v2', initial_value=2.0)",
        "        .add_parameter('p1', value=1.0)",
        "        .add_parameter('p2', value=2.0)",
        "        .add_derived(",
        "                'd1',",
        "                fn=add,",
        "                args=['v1', 'v2'],",
        "            )",
        "        .add_derived(",
        "                'd2',",
        "                fn=mul,",
        "                args=['v1', 'v2'],",
        "            )",
        "        .add_reaction(",
        '                "r1",',
        "                fn=mass_action_1s,",
        "                args=['v1', 'p1'],",
        '                stoichiometry={"v1": -1.0,"v2": 1.0},',
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_2v_2p_2d_2r() -> None:
    assert generate_mxlpy_code_raw(models.m_2v_2p_2d_2r()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_ADD_LINES,
        "",
        "",
        *_MUL_LINES,
        "",
        "",
        *_MASS_ACTION_1S_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_variable('v2', initial_value=2.0)",
        "        .add_parameter('p1', value=1.0)",
        "        .add_parameter('p2', value=2.0)",
        "        .add_derived(",
        "                'd1',",
        "                fn=add,",
        "                args=['v1', 'p1'],",
        "            )",
        "        .add_derived(",
        "                'd2',",
        "                fn=mul,",
        "                args=['v2', 'p2'],",
        "            )",
        "        .add_reaction(",
        '                "r1",',
        "                fn=mass_action_1s,",
        "                args=['v1', 'd1'],",
        '                stoichiometry={"v1": -1.0,"v2": 1.0},',
        "            )",
        "        .add_reaction(",
        '                "r2",',
        "                fn=mass_action_1s,",
        "                args=['v2', 'd2'],",
        '                stoichiometry={"v1": 1.0,"v2": -1.0},',
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_dependent_derived() -> None:
    assert generate_mxlpy_code_raw(models.m_dependent_derived()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_CONSTANT_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_parameter('p1', value=1.0)",
        "        .add_derived(",
        "                'd1',",
        "                fn=constant,",
        "                args=['p1'],",
        "            )",
        "        .add_derived(",
        "                'd2',",
        "                fn=constant,",
        "                args=['d1'],",
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_derived_stoichiometry() -> None:
    assert generate_mxlpy_code_raw(models.m_derived_stoichiometry()).split("\n") == [
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        *_CONSTANT_LINES,
        "",
        "",
        *_ONE_DIV_LINES,
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_reaction(",
        '                "r1",',
        "                fn=constant,",
        "                args=['v1'],",
        "                stoichiometry={\"v1\": Derived(fn=one_div, args=['v1'])},",
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_1v_1p_0d_0r_1qss() -> None:
    assert generate_mxlpy_code_raw(models.m_1v_1p_0d_0r_1qss()).split("\n") == [
        "from mxlpy.surrogates import qss",
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        "def qss_two_outputs(v1: float, p1: float) -> tuple[float, float]:",
        "    return v1 * p1, v1 + p1",
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_parameter('p1', value=1.0)",
        "        .add_surrogate(",
        "                'qss1',",
        "                qss.Surrogate(",
        "                    model=qss_two_outputs,",
        "                    args=['v1', 'p1'],",
        "                    outputs=['out1', 'out2'],",
        '                    stoichiometries={"r1": {"v1": -1.0}},',
        "                ),",
        "            )",
        "    )",
    ]


def test_generate_model_code_py_m_1v_0p_0d_0r_1qss() -> None:
    assert generate_mxlpy_code_raw(models.m_1v_0p_0d_0r_1qss()).split("\n") == [
        "from mxlpy.surrogates import qss",
        "from mxlpy import Model, Derived, InitialAssignment",
        "",
        "def qss_single_output(v1: float) -> tuple[float]:",
        "    return (v1 * 2.0,)",
        "",
        "",
        "def create_model() -> Model:",
        "    return (",
        "        Model()",
        "        .add_variable('v1', initial_value=1.0)",
        "        .add_surrogate(",
        "                'qss1',",
        "                qss.Surrogate(",
        "                    model=qss_single_output,",
        "                    args=['v1'],",
        "                    outputs=['out1'],",
        '                    stoichiometries={"r1": {"v1": -1.0}},',
        "                ),",
        "            )",
        "    )",
    ]
