name: ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  default-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.13.12

      - name: Set Python version
        run: uv venv --python 3.13.12

      - name: Set up minimal environment
        run: uv sync

      - name: Check that import always works
        run: uv run python -c "import mxlpy"

      - name: Set up maximal environment
        run: uv sync --all-extras --all-groups

      - name: Run tests
        run: uv run pytest --disable-warnings tests/
