name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up environment
        run: uv sync --extra dev --extra torch

      - name: Run tests
        run: uv run pytest --disable-warnings --cov --cov-report json tests/

      - name: Coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 98ab3ce1db511de42f9871e91d85e4cd
          filename: coverage.json
